In [ ]:
import numpy as np

In [ ]:
# using np.array to create NumPy matrix

# 1-D array of size = 7
one_dimensional_arr = np.array([1,2,3,4,5,6,7])
print(one_dimensional_arr)
#print value of index 5
print(one_dimensional_arr[5])  

# 2-D array of size = (4,2)
two_dimensional_arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(two_dimensional_arr)
# print value at row = 2 and column = 1
print(two_dimensional_arr[1][1])  

[1 2 3 4 5 6 7]
6
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
4


In [ ]:
# creating an array with sequence of integers using np.arange(a,b) 
# where a is the lower bound (included) and b is the upper bound (excluded)
seq_int = np.arange(30,100)
print(seq_int)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77
 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [ ]:
# creating a 2-D array using np.arange
two_dimensional_seq = np.arange(100,200).reshape(10,10)
print(two_dimensional_seq)

[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


In [ ]:
# creating an array with random floating point values using np.random.random
floating_val = np.random.random([10])
print(floating_val)



[0.94706623 0.12579926 0.81706834 0.92744851 0.8104341  0.3035704
 0.72205482 0.06614902 0.62702914 0.3667462 ]


In [ ]:
# create an floating-point array in a range of -10 to 10
arr = (np.random.random([5]*2))-10
print(arr)

[[-9.28693531 -9.55924178 -9.47325674 -9.2053433  -9.51589986]
 [-9.99341928 -9.91366263 -9.38529714 -9.51663401 -9.58291789]
 [-9.35704551 -9.20283611 -9.79765183 -9.5421631  -9.7447038 ]
 [-9.94223861 -9.30216518 -9.1780997  -9.38417236 -9.68591792]
 [-9.17964317 -9.01298337 -9.84252133 -9.36807302 -9.72690727]]


In [ ]:
# create 3x4 matrix of floating-point values
matrix = np.random.random(size=(3,4))
print(matrix)

[[0.79027913 0.95558064 0.24413362 0.4077185 ]
 [0.33475953 0.86653519 0.46223432 0.54581714]
 [0.93818963 0.7073354  0.19403873 0.95479883]]


In [ ]:
# create 4x5 matrix filled with all ones
ones_arr = np.ones(shape=(4,5))
print(ones_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# create an array with low and high values given
array = np.random.randint(low=10, high=90, size=(2,3))
print(array)

[[39 36 55]
 [22 55 35]]


In [ ]:
# creates a m * n array filled with the given value
array_with_one_val = np.full((4,5),6)
print(array_with_one_val)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [ ]:
# using empty function creates an array. Its initial content is random and depends on the state of the memory.
empty_arr = np.empty((2,3))
print(empty_arr)

[[1.7016887e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [ ]:
# create an array with the diagonal 1s and the others 0
diagonal_arr = np.eye(4,4)
print(diagonal_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# The function linspace returns evenly spaced numbers over a specified interval. 
# For example, the below function returns five equally spaced numbers between the interval 0 and 16.
linspace_arr = np.linspace(0,20, num=3)
print(linspace_arr)

[[ 0. 10. 20.]]


In [ ]:
# create 2-D array using linspace
two_dim_Arr = np.linspace([2,20],[10,40],num=5)
print(two_dim_Arr)

[[ 2. 20.]
 [ 4. 25.]
 [ 6. 30.]
 [ 8. 35.]
 [10. 40.]]
